name: apptemplate
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  async: ^2.11.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.12.2
  cloud_firestore_odm: ^1.0.0-dev.74
  collection: ^1.17.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.3
  firebase_messaging: ^14.7.3
  firebase_remote_config: ^4.3.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_svg: ^2.0.9
  flutter_vibrate: ^1.3.0
  fluttertoast: ^8.2.2
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.1.5
  hooks_riverpod: ^2.4.5
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  package_info_plus: ^4.2.0
  recase: ^4.1.0
  riverpod: ^2.4.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  stack_trace: ^1.11.0
  synchronized: ^3.1.0
  url_launcher: ^6.2.1
  uuid: ^4.1.0
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.73
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#415d5e"
  adaptive_icon_foreground: "assets/app_icon/app_icon_android.png"
  web:
    generate: true
    image_path: "assets/app_icon/app_icon.png"
    background_color: "#415d5e"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Thin.ttf
          weight: 100
        - asset: assets/font/Lato-Light.ttf
          weight: 300
        - asset: assets/font/Lato-Regular.ttf
          weight: 400
        - asset: assets/font/Lato-Bold.ttf
          weight: 700
        - asset: assets/font/Lato-Black.ttf
          weight: 900
